<LupusPlayerCard>

    size_hint_y: None
    height: "90dp"

    padding: "15dp"

    spacing: "15dp"

    canvas.before:
        Color:
            rgba:
                (.60,.15,.15,1) if root.host else (.16,.16,.16,1)

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [15]

    MDLabel:

        text:
            "👑" if root.host else "🙂"

        font_style: "Headline"

        size_hint_x: None

        width: "50dp"

    MDBoxLayout:

        orientation: "vertical"

        MDLabel:

            text: root.player_name

            bold: True

            font_style: "Title"

        MDLabel:

            text: root.role

            theme_text_color: "Hint"

    MDLabel:

        text:
            "🟢 Pronto" if root.ready else "🟠 Attesa"

        halign: "right"

        size_hint_x: .45